# Generated by Django 5.0.1 on 2024-01-15 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_rename_tounament_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="tournament",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.tournament",
            ),
        ),
    ]
