# Generated by Django 5.0.1 on 2024-01-15 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
