# Generated by Django 5.0.1 on 2024-01-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_account_team_team_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="member",
        ),
        migrations.AddField(
            model_name="account",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="account.team",
            ),
        ),
    ]
